server:
  port: 9018

xywg:
  #netty-position-port: 9072  #监听端口 58.221.137.62:9061
  netty-position-port: 9560 #监听端口 58.221.137.62:9560
  redisHead: lian-wu-yun1
  upgrade-file-base-path: /upgrade/    #升级文件在本地的存储基础地址
  ############# node #############
  node:
    enabled: true
    name: lianwuyun1
    url: 192.168.20.160:${server.port}
  websocket:
    allowed-origins: http://localhost:8081,http://localhost:8080,http://192.168.1.186:8080,http://192.168.1.186:8081
  log:
    enabled: false
ali:
  accessKeyId: LTAIM7w6KjwRXGxP
  accessKeySecret: 2Ixpjf7Dl3EGjvbqe3AziYIoFjL5mL
  iosAppKey: 25052872
  androidAppKey: 25054797
  env: DEV #DEV,PRODUCT

spring:
  redis:
        database: 0
        host: 121.43.151.100
        port: 6379
        password: duanjudy@123
        timeout: 10000
        jedis:
          pool:
            max-active: 8 #连接池最大连接数(使用负值表示没有限制)
            max-wait: -1  #连接池最大阻塞等待时间(负值表示没有限制)
            max-idle: 5  #连接池中的最大空闲连接
            min-idle: 0  #连接池中最小的空闲连接
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
      imagePath: /labor/
      imageLocalPath: http://192.168.1.124:8080/labor/
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: xywg-admin/src
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
##############数据库######################
  datasource:
    url: jdbc:mysql://118.31.69.25:3306/iot_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Xingyun*_001
    db-name: device_platform
    filters: log4j,mergeStat
#############日志##################
logging:
  level.root: info
  level.com.stylefeng: debug
  path: E;//logs//iot
  file: xywg.log

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:**/mapping/*.xml
  typeAliasesPackage: com.xywg.iot.*.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    metaObjectHandler: com.xywg.iot.aop.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用



ftp:
  host: 192.168.1.209
  port: 21
  username: smartsite
  password: 123456
  root-path: industrial_iot