

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:**/mapper/xml/*.xml
  typeAliasesPackage: com.wyf.rabbitmqtest.rabbitadmin.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #  metaObjectHandler: com.xywg.iot.aop.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


spring:
##############数据库######################
  datasource:
    url: jdbc:mysql://118.31.69.25:3306/rabbitmq_admin?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Xingyun*_001
    db-name: xyiothubdemo
    filters: log4j,mergeStat
  rabbitmq:
      username: guest
      password: guest
      addresses: 118.24.111.210:5672
      publisher-confirms: true #发送确认
      publisher-returns: true   #返回错误确认
      listener:
        direct:
          acknowledge-mode: manual
        simple:
          acknowledge-mode: manual
server:
  port: 7575