server:
  port: 7766
spring:
  security:
    user:
      name: admin
      password: 123456
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone:  ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/