##########################################################
##################  所有dev的配置  #################
##########################################################

server:
  port: 8099
###################  spring配置  ###################



###################  redis配置  ###################
spring:
############### i18n #####################
  messages:
    encoding: UTF-8
    basename: i18n.xywg
##############数据库######################
  datasource:
    url: jdbc:mysql://118.31.69.25:3306/iot_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Xingyun*_001
    db-name: xyiothubdemo
    filters: log4j,mergeStat

#  rabbitmq:
#        username: admin
#        password: admin
#        #virtualHost: XXX
#        addresses: 192.168.1.199:5672
#        publisher-confirms: true
################## redis ######################
  redis:
      database: 0
      host: 121.43.151.100
      port: 6379
      password: duanjudy@123
      timeout: 10000
      jedis:
        pool:
          max-active: 8 #连接池最大连接数(使用负值表示没有限制)
          max-wait: -1  #连接池最大阻塞等待时间(负值表示没有限制)
          max-idle: 5  #连接池中的最大空闲连接
          min-idle: 0  #连接池中最小的空闲连接



###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:**/dao/mapping/*.xml
  typeAliasesPackage: com.xywg.iot.modular.*.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    metaObjectHandler: com.xywg.iot.aop.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

####################  netty ########################

netty:
  port: 9628
  node-name: iothub1
  timeout: 360   #超时时间,单位秒、


####################  zbus ##############################
zbus:
  host: 192.168.1.64:15555
  topic-iothub: iothub
  topic-cloud: cloud
cache:
  header: iot
  open: true

################# jwt #########################
jwt:
  token-header: iot
  user-header: user
  random-header: random

############ baidu ########################
baidu:
  ak: WghvHai6aTePM1YlgoZ5dbQ8s4TU91Cv

############### 健康节点 ####################
management:
  endpoint:
    health:
      show-details: when_authorized #带权限的可以查看明细，否则只能看节点状态
      roles: ["THIRD"]
  endpoints:
    web:
      exposure:
        include: ["*"]
############ xywg #########
xywg:
#########  日志 #########
  log:
    enabled: true

############# cache ##########
  xycache:
    enabled: true
############# node #############
  node:
    enabled: true
    name: iothub1
    url: 192.168.20.160:${server.port}












