##########################################################
##################  所有dev的配置  #################
##########################################################

server:
  port: 9560


###################  spring配置  ###################

spring:
############### i18n #####################
  messages:
    encoding: UTF-8
    basename: i18n.xywg

##############数据库######################
#  datasource:
#    url: jdbc:mysql://118.31.69.25:3306/iot_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
#    username: root
#    password: Xingyun*_001
#    db-name: xyiothubdemo
#    filters: log4j,mergeStat
################## redis ######################
  redis:
      database: 0
      host: 121.43.151.100
      port: 6379
      password: duanjudy@123
      timeout: 10000
      jedis:
        pool:
          max-active: 8 #连接池最大连接数(使用负值表示没有限制)
          max-wait: -1  #连接池最大阻塞等待时间(负值表示没有限制)
          max-idle: 5  #连接池中的最大空闲连接
          min-idle: 0  #连接池中最小的空闲连接



  data:
    mongodb:
      uri: mongodb://test:111111@192.168.1.211:27017/?authSource=iothub
      database: iothub



####################  zbus ##############################
zbus:
  host: 192.168.1.64:15555
  topic-iothub: iothub
  topic-cloud: cloud
###################   cache ###############################

cache:
  header: iot
  open: true

xywg:
  log:
    enabled : true
logging:
  level:
    root: debug








