##########################################################
###########################   水表   ###############################
##########################################################

####################  netty ########################

netty:
  port: 9012 #监听的端口
  iotNettyPort: 9012      #转发的端口











