##########################################################
###########################   安全帽   ###############################
##########################################################

####################  netty ########################

netty:
  port: 9013 #监听的端口
  iotNettyPort: 9013      #转发的端口











