##########################################################
##################  所有dev的配置  #################
##########################################################


####################  netty ########################

netty:
  port: 9627 #监听的端口
  iotNettyUrl: 192.168.1.64   #转发的IP
  iotNettyPort: 9060      #转发的端口















