##########################################################
###########################   星云网格   ###############################
#######################   扬尘 转发的配置  #################
##########################################################

####################  netty ########################

netty:
  port: 9095 #监听的端口
  iotNettyPort: 9095      #转发的端口











