##########################################################
###########################   安徽聚正   ###############################
#######################   升降机 转发的配置  #################
##########################################################

####################  netty ########################

netty:
  port: 9072 #监听的端口
  iotNettyPort: 9072      #转发的端口











