##########################################################
###########################   安徽聚正   ###############################
#######################   塔吊 转发的配置  #################
##########################################################

####################  netty ########################

netty:
  port: 9071 #监听的端口
  iotNettyPort: 9071      #转发的端口











