##########################################################
###########################   大连   ###############################
#######################扬尘/塔吊/升降机 转发的配置  #################
##########################################################

####################  netty ########################

netty:
  port: 9060 #监听的端口
  iotNettyPort: 9060      #转发的端口











