##########################################################
###########################   公司沙盘   ###############################
##########################################################

####################  netty ########################

netty:
  port: 9001 #监听的端口
  iotNettyPort: 9001      #转发的端口











