##########################################################
###########################   星云网格   ###############################
#######################   塔吊 转发的配置  #################
##########################################################

####################  netty ########################

netty:
  port: 9096 #监听的端口
  iotNettyPort: 9096      #转发的端口











