##########################################################
###########################   电表   ###############################
##########################################################

####################  netty ########################

netty:
  port: 9011 #监听的端口
  iotNettyPort: 9011      #转发的端口











